# global default

build_task:
  container:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2-alpine
  install_script: 
    - apk add --update nodejs npm
    - dotnet build

test_task:
  container:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2-alpine
  test_script: 
    - dotnet test